version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my_app
permissions:
  - object: /home/ec2-user/my_app/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
<<<<<<< HEAD
      runas: ec2-user
=======
      runas: ec2-user
>>>>>>> 29c1d08a954c130fca9af76a111b88dd878d7692
